//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.Grow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.Grow.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveStatusType {
            get {
                return ResourceManager.GetString("ActiveStatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grow Your Skills.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project owner.
        /// </summary>
        public static string AuthorText {
            get {
                return ResourceManager.GetString("AuthorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string BlockedStatusType {
            get {
                return ResourceManager.GetString("BlockedStatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Discover and join&lt;/b&gt; projects/opportunities that interests you to learn and acquire new skills. &lt;br /&gt;
        ///&lt;b&gt;View the skills&lt;/b&gt; acquired across multiple projects at one place.
        /// &lt;br /&gt;
        ///&lt;b&gt;Create projects&lt;/b&gt; to give opportunity for your co-workers to grow..
        /// </summary>
        public static string CarouselCard1Text {
            get {
                return ResourceManager.GetString("CarouselCard1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Endorse&lt;/b&gt; team members and send a personal note during project closure.&lt;br /&gt;&lt;b&gt;Get notified&lt;/b&gt; on project related updates to manage effectively..
        /// </summary>
        public static string CarouselCard2Text {
            get {
                return ResourceManager.GetString("CarouselCard2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Add the app&lt;/b&gt; to the Channel Tab based on skills to learn together with your team.
        ///&lt;br /&gt;
        ///&lt;b&gt;Share the projects&lt;/b&gt; that you have created or part of in a channel or chat to learn together..
        /// </summary>
        public static string CarouselCard3Text {
            get {
                return ResourceManager.GetString("CarouselCard3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string ChatButton {
            get {
                return ResourceManager.GetString("ChatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string ClosedStatusType {
            get {
                return ResourceManager.GetString("ClosedStatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project team update.
        /// </summary>
        public static string CongratulationsMessage {
            get {
                return ResourceManager.GetString("CongratulationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I told {0} that you&apos;d be in touch..
        /// </summary>
        public static string ConnectWithUserMessage {
            get {
                return ResourceManager.GetString("ConnectWithUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again in a few minutes..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to skills.
        /// </summary>
        public static string GoToSkillsCardButton {
            get {
                return ResourceManager.GetString("GoToSkillsCardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to join a different project?.
        /// </summary>
        public static string joinProjectAfterDelete {
            get {
                return ResourceManager.GetString("joinProjectAfterDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string MessagingExtensionCardViewProjectDetailButtonText {
            get {
                return ResourceManager.GetString("MessagingExtensionCardViewProjectDetailButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your monthly digest.
        /// </summary>
        public static string NotificationCardMonthlyTitleText {
            get {
                return ResourceManager.GetString("NotificationCardMonthlyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your weekly digest.
        /// </summary>
        public static string NotificationCardWeeklyTitleText {
            get {
                return ResourceManager.GetString("NotificationCardWeeklyTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View more.
        /// </summary>
        public static string NotificationListCardViewMoreButtonText {
            get {
                return ResourceManager.GetString("NotificationListCardViewMoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string NotStartedStatusType {
            get {
                return ResourceManager.GetString("NotStartedStatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open item.
        /// </summary>
        public static string OpenItem {
            get {
                return ResourceManager.GetString("OpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all projects.
        /// </summary>
        public static string PersonalWelcomeCardDiscoverButtonText {
            get {
                return ResourceManager.GetString("PersonalWelcomeCardDiscoverButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has closed the project &apos;**{1}**&apos;.
        /// </summary>
        public static string ProjectClosedMessage {
            get {
                return ResourceManager.GetString("ProjectClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project &apos;**{1}**&apos; was deleted by **{0}** and is now unavailable to join..
        /// </summary>
        public static string ProjectDeletedMessage {
            get {
                return ResourceManager.GetString("ProjectDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project details.
        /// </summary>
        public static string ProjectDetails {
            get {
                return ResourceManager.GetString("ProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string ProjectDurationText {
            get {
                return ResourceManager.GetString("ProjectDurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** has joined your project &apos;**{1}**&apos;.
        /// </summary>
        public static string ProjectJoinedMessage {
            get {
                return ResourceManager.GetString("ProjectJoinedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** has removed you from the project &apos;**{1}**&apos;.
        /// </summary>
        public static string ProjectRemovalMessage {
            get {
                return ResourceManager.GetString("ProjectRemovalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project status icon.
        /// </summary>
        public static string ProjectStatusIcon {
            get {
                return ResourceManager.GetString("ProjectStatusIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are some of the skills {0} has endorsed you..
        /// </summary>
        public static string SkillsEndorsedMessage {
            get {
                return ResourceManager.GetString("SkillsEndorsedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills needed.
        /// </summary>
        public static string SkillsLabelText {
            get {
                return ResourceManager.GetString("SkillsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!.
        /// </summary>
        public static string SorryMessage {
            get {
                return ResourceManager.GetString("SorryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All projects.
        /// </summary>
        public static string TabName {
            get {
                return ResourceManager.GetString("TabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team size.
        /// </summary>
        public static string TeamSizeText {
            get {
                return ResourceManager.GetString("TeamSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string TeamWelcomeCardConfigureButtonText {
            get {
                return ResourceManager.GetString("TeamWelcomeCardConfigureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try other new projects and acquire skills..
        /// </summary>
        public static string TryNewProjectsMessage {
            get {
                return ResourceManager.GetString("TryNewProjectsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m the Grow Your Skills bot, and I&apos;m here to help your team acquire new skills and gain on-the-job experiences by connecting people with projects..
        /// </summary>
        public static string WelcomeCardContent {
            get {
                return ResourceManager.GetString("WelcomeCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here&apos;s what you can do:
        ///- Post your own project, requesting help from people with specific skills.
        ///- Discover projects to join based on skills you&apos;d like to acquire or people you&apos;d like to learn from.
        ///- Get endorsed for the skills you contribute to the projects you join..
        /// </summary>
        public static string WelcomeCardDescriptionText {
            get {
                return ResourceManager.GetString("WelcomeCardDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started!.
        /// </summary>
        public static string WelcomeCardGetStartedText {
            get {
                return ResourceManager.GetString("WelcomeCardGetStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a **digest of content** that are added based on your preference in a channel to stay updated on the topics..
        /// </summary>
        public static string WelcomeCardTeamDigestContent {
            get {
                return ResourceManager.GetString("WelcomeCardTeamDigestContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Search &amp; Share** your favorite reads in a channel or chat to help your Peers grow..
        /// </summary>
        public static string WelcomeCardTeamShareContent {
            get {
                return ResourceManager.GetString("WelcomeCardTeamShareContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
    }
}
